import struct

from openc3.conversions.conversion import Conversion


def _parse_int(data, offset, size, signed):
    code = {8: "b", 16: "h", 32: "i", 64: "q"}[size]
    if not signed:
        code = code.upper()
    val = struct.unpack_from(">" + code, data, offset)[0]
    return val, offset + size // 8


def _parse_float(data, offset, size):
    code = "f" if size == 32 else "d"
    val = struct.unpack_from(">" + code, data, offset)[0]
    return val, offset + size // 8


def _parse_string(data, offset):
    length, offset = _parse_int(data, offset, 32, False)
    s = bytes(data[offset:offset + length]).decode("utf-8", errors="replace")
    return s, offset + length


def _parse_param(data, offset, param):
    kind = param["kind"]
    if kind == "integer":
        return _parse_int(data, offset, param["size"], param.get("signed", False))
    if kind == "float":
        return _parse_float(data, offset, param["size"])
    if kind == "string":
        return _parse_string(data, offset)
    if kind == "bool":
        val, offset = _parse_int(data, offset, param.get("size", 8), False)
        return bool(val), offset
    if kind == "enum":
        rep = param["representationType"]
        val, offset = _parse_int(data, offset, rep["size"], rep.get("signed", False))
        states = param.get("states", {})
        return states.get(val, val), offset
    if kind == "array":
        elem = param["elementType"]
        items = []
        for _ in range(param["size"]):
            v, offset = _parse_param(data, offset, elem)
            items.append(v)
        return items, offset
    raise RuntimeError(f"Unhandled event param kind: {kind}")


EVENTS = { 16902: { 'name': 'ServerDeployment.fatalAdapter.AF_ASSERT_6',
           'severity': 'FATAL',
           'format': 'Assert in file {}, line {}: {} {} {} {} {} {}',
           'params': [ {'kind': 'string', 'size': 200, 'name': 'file'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'line'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'arg1'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'arg2'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'arg3'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'arg4'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'arg5'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'arg6'}]},
  1286: { 'name': 'ServerDeployment.cmdDisp.TooManyCommands',
          'severity': 'WARNING_HI',
          'format': 'Too many outstanding commands. opcode=0x{:x}',
          'params': [{'kind': 'integer', 'size': 32, 'signed': False, 'name': 'Opcode'}]},
  2315: { 'name': 'ServerDeployment.fileManager.RemoveFileSucceeded',
          'severity': 'ACTIVITY_HI',
          'format': 'Removed file {} successfully',
          'params': [{'kind': 'string', 'size': 256, 'name': 'fileName'}]},
  1024: { 'name': 'ServerDeployment.rateGroup3.RateGroupStarted',
          'severity': 'DIAGNOSTIC',
          'format': 'Rate group started.',
          'params': []},
  2306: { 'name': 'ServerDeployment.fileManager.FileMoveError',
          'severity': 'WARNING_HI',
          'format': 'Could not move file {} to file {}, returned status {}',
          'params': [ {'kind': 'string', 'size': 256, 'name': 'sourceFileName'},
                      {'kind': 'string', 'size': 256, 'name': 'destFileName'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'status'}]},
  1559: { 'name': 'ServerDeployment.cmdSeq.CS_JoinWaiting',
          'severity': 'ACTIVITY_HI',
          'format': 'Start waiting for sequence file {}: Command {} (opcode {}) to complete',
          'params': [ {'kind': 'string', 'size': 60, 'name': 'filename'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'recordNumber'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'opCode'}]},
  1549: { 'name': 'ServerDeployment.cmdSeq.CS_TimeBaseMismatch',
          'severity': 'WARNING_HI',
          'format': "Sequence file {}: Current time base doesn't match sequence time: base: {} seq: {}",
          'params': [ {'kind': 'string', 'size': 60, 'name': 'fileName'},
                      {'kind': 'integer', 'size': 16, 'signed': False, 'name': 'time_base'},
                      {'kind': 'integer', 'size': 16, 'signed': False, 'name': 'seq_time_base'}]},
  1554: { 'name': 'ServerDeployment.cmdSeq.CS_NoSequenceActive',
          'severity': 'WARNING_LO',
          'format': 'No sequence active.',
          'params': []},
  16898: { 'name': 'ServerDeployment.fatalAdapter.AF_ASSERT_2',
           'severity': 'FATAL',
           'format': 'Assert in file {}, line {}: {} {}',
           'params': [ {'kind': 'string', 'size': 200, 'name': 'file'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'line'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'arg1'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'arg2'}]},
  2309: { 'name': 'ServerDeployment.fileManager.AppendFileFailed',
          'severity': 'WARNING_HI',
          'format': 'Appending {} onto {} failed with status {}',
          'params': [ {'kind': 'string', 'size': 256, 'name': 'source'},
                      {'kind': 'string', 'size': 256, 'name': 'target'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'status'}]},
  1290: { 'name': 'ServerDeployment.cmdDisp.OpCodeReregistered',
          'severity': 'DIAGNOSTIC',
          'format': 'Opcode 0x{:x} is already registered to port {}',
          'params': [ {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'Opcode'},
                      {'kind': 'integer', 'size': 32, 'signed': True, 'name': 'port'}]},
  1544: { 'name': 'ServerDeployment.cmdSeq.CS_CommandComplete',
          'severity': 'ACTIVITY_LO',
          'format': 'Sequence file {}: Command {} (opcode {}) complete',
          'params': [ {'kind': 'string', 'size': 60, 'name': 'fileName'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'recordNumber'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'opCode'}]},
  3332: { 'name': 'ServerDeployment.prmDb.PrmFileWriteError',
          'severity': 'WARNING_HI',
          'format': 'Parameter write failed in stage {} with record {} and error {}',
          'params': [ { 'kind': 'enum',
                        'representationType': {'name': 'I32', 'kind': 'integer', 'size': 32, 'signed': True},
                        'states': { 0: 'OPEN',
                                    1: 'DELIMITER',
                                    2: 'DELIMITER_SIZE',
                                    3: 'RECORD_SIZE',
                                    4: 'RECORD_SIZE_SIZE',
                                    5: 'PARAMETER_ID',
                                    6: 'PARAMETER_ID_SIZE',
                                    7: 'PARAMETER_VALUE',
                                    8: 'PARAMETER_VALUE_SIZE'},
                        'name': 'stage'},
                      {'kind': 'integer', 'size': 32, 'signed': True, 'name': 'record'},
                      {'kind': 'integer', 'size': 32, 'signed': True, 'name': 'error'}]},
  2316: { 'name': 'ServerDeployment.fileManager.AppendFileStarted',
          'severity': 'ACTIVITY_HI',
          'format': 'Appending file {} to the end of {}...',
          'params': [ {'kind': 'string', 'size': 256, 'name': 'source'},
                      {'kind': 'string', 'size': 256, 'name': 'target'}]},
  3335: { 'name': 'ServerDeployment.prmDb.PrmFileLoadComplete',
          'severity': 'ACTIVITY_HI',
          'format': 'Parameter file load completed. Read {} records.',
          'params': [{'kind': 'integer', 'size': 32, 'signed': False, 'name': 'records'}]},
  2819: { 'name': 'ServerDeployment.eventLogger.ID_FILTER_REMOVED',
          'severity': 'ACTIVITY_HI',
          'format': 'ID filter ID {} removed.',
          'params': [{'kind': 'integer', 'size': 32, 'signed': False, 'name': 'ID'}]},
  1287: { 'name': 'ServerDeployment.cmdDisp.NoOpReceived',
          'severity': 'ACTIVITY_HI',
          'format': 'Received a NO-OP command',
          'params': []},
  1792: { 'name': 'ServerDeployment.comQueue.QueueOverflow',
          'severity': 'WARNING_HI',
          'format': 'The {} queue at index {} overflowed',
          'params': [ { 'kind': 'enum',
                        'representationType': {'name': 'I32', 'kind': 'integer', 'size': 32, 'signed': True},
                        'states': {0: 'COM_QUEUE', 1: 'BUFFER_QUEUE'},
                        'name': 'queueType'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'index'}]},
  2562: { 'name': 'ServerDeployment.fileUplink.FileReceived',
          'severity': 'ACTIVITY_HI',
          'format': 'Received file {}',
          'params': [{'kind': 'string', 'size': 40, 'name': 'fileName'}]},
  1545: { 'name': 'ServerDeployment.cmdSeq.CS_SequenceComplete',
          'severity': 'ACTIVITY_HI',
          'format': 'Sequence file {} complete',
          'params': [{'kind': 'string', 'size': 60, 'name': 'fileName'}]},
  2049: { 'name': 'ServerDeployment.fileDownlink.FileReadError',
          'severity': 'WARNING_HI',
          'format': 'Could not read file {} with status {}',
          'params': [ {'kind': 'string', 'size': 100, 'name': 'fileName'},
                      {'kind': 'integer', 'size': 32, 'signed': True, 'name': 'status'}]},
  2324: { 'name': 'ServerDeployment.fileManager.FileSizeStarted',
          'severity': 'ACTIVITY_HI',
          'format': 'Checking size of file {}...',
          'params': [{'kind': 'string', 'size': 256, 'name': 'fileName'}]},
  16897: { 'name': 'ServerDeployment.fatalAdapter.AF_ASSERT_1',
           'severity': 'FATAL',
           'format': 'Assert in file {}, line {}: {}',
           'params': [ {'kind': 'string', 'size': 200, 'name': 'file'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'line'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'arg1'}]},
  8196: { 'name': 'ServerDeployment.health.HLTH_CHECK_PING',
          'severity': 'ACTIVITY_HI',
          'format': 'Health checking set to {} for {}',
          'params': [ { 'kind': 'enum',
                        'representationType': {'name': 'I32', 'kind': 'integer', 'size': 32, 'signed': True},
                        'states': {0: 'DISABLED', 1: 'ENABLED'},
                        'name': 'enabled'},
                      {'kind': 'string', 'size': 40, 'name': 'entry'}]},
  1283: { 'name': 'ServerDeployment.cmdDisp.OpCodeError',
          'severity': 'COMMAND',
          'format': 'Opcode 0x{:x} completed with error {}',
          'params': [ {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'Opcode'},
                      { 'kind': 'enum',
                        'representationType': {'name': 'I32', 'kind': 'integer', 'size': 32, 'signed': True},
                        'states': { 0: 'OK',
                                    1: 'INVALID_OPCODE',
                                    2: 'VALIDATION_ERROR',
                                    3: 'FORMAT_ERROR',
                                    4: 'EXECUTION_ERROR',
                                    5: 'BUSY'},
                        'name': 'error'}]},
  512: { 'name': 'ServerDeployment.rateGroup1.RateGroupStarted',
         'severity': 'DIAGNOSTIC',
         'format': 'Rate group started.',
         'params': []},
  2307: { 'name': 'ServerDeployment.fileManager.FileRemoveError',
          'severity': 'WARNING_HI',
          'format': 'Could not remove file {}, returned status {}',
          'params': [ {'kind': 'string', 'size': 256, 'name': 'fileName'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'status'}]},
  2560: { 'name': 'ServerDeployment.fileUplink.BadChecksum',
          'severity': 'WARNING_HI',
          'format': 'Bad checksum value during receipt of file {}: computed 0x{:x}, read 0x{:x}',
          'params': [ {'kind': 'string', 'size': 40, 'name': 'fileName'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'computed'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'read'}]},
  8199: { 'name': 'ServerDeployment.health.HLTH_PING_INVALID_VALUES',
          'severity': 'WARNING_HI',
          'format': 'Health ping for {} invalid values: WARN {} FATAL {}',
          'params': [ {'kind': 'string', 'size': 40, 'name': 'entry'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'warn'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'fatal'}]},
  1560: { 'name': 'ServerDeployment.cmdSeq.CS_JoinWaitingNotComplete',
          'severity': 'WARNING_HI',
          'format': 'Still waiting for sequence file to complete',
          'params': []},
  2565: { 'name': 'ServerDeployment.fileUplink.PacketOutOfBounds',
          'severity': 'WARNING_HI',
          'format': 'Packet {} out of bounds for file {}',
          'params': [ {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'packetIndex'},
                      {'kind': 'string', 'size': 40, 'name': 'fileName'}]},
  2313: { 'name': 'ServerDeployment.fileManager.RemoveDirectorySucceeded',
          'severity': 'ACTIVITY_HI',
          'format': 'Removed directory {} successfully',
          'params': [{'kind': 'string', 'size': 256, 'name': 'dirName'}]},
  1281: { 'name': 'ServerDeployment.cmdDisp.OpCodeDispatched',
          'severity': 'COMMAND',
          'format': 'Opcode 0x{:x} dispatched to port {}',
          'params': [ {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'Opcode'},
                      {'kind': 'integer', 'size': 32, 'signed': True, 'name': 'port'}]},
  16899: { 'name': 'ServerDeployment.fatalAdapter.AF_ASSERT_3',
           'severity': 'FATAL',
           'format': 'Assert in file {}, line {}: {} {} {}',
           'params': [ {'kind': 'string', 'size': 200, 'name': 'file'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'line'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'arg1'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'arg2'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'arg3'}]},
  1555: { 'name': 'ServerDeployment.cmdSeq.CS_SequenceValid',
          'severity': 'ACTIVITY_HI',
          'format': 'Sequence {} is valid.',
          'params': [{'kind': 'string', 'size': 60, 'name': 'filename'}]},
  2820: { 'name': 'ServerDeployment.eventLogger.ID_FILTER_NOT_FOUND',
          'severity': 'WARNING_LO',
          'format': 'ID filter ID {} not found.',
          'params': [{'kind': 'integer', 'size': 32, 'signed': False, 'name': 'ID'}]},
  1541: { 'name': 'ServerDeployment.cmdSeq.CS_FileSizeError',
          'severity': 'WARNING_HI',
          'format': 'Sequence file {} too large. Size: {}',
          'params': [ {'kind': 'string', 'size': 60, 'name': 'fileName'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'size'}]},
  1540: { 'name': 'ServerDeployment.cmdSeq.CS_RecordInvalid',
          'severity': 'WARNING_HI',
          'format': 'Sequence file {}: Record {} invalid. Err: {}',
          'params': [ {'kind': 'string', 'size': 60, 'name': 'fileName'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'recordNumber'},
                      {'kind': 'integer', 'size': 32, 'signed': True, 'name': 'error'}]},
  2323: { 'name': 'ServerDeployment.fileManager.FileSizeError',
          'severity': 'WARNING_HI',
          'format': 'Failed to get the size of file {}, returned status {}',
          'params': [ {'kind': 'string', 'size': 256, 'name': 'fileName'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'status'}]},
  2561: { 'name': 'ServerDeployment.fileUplink.FileOpenError',
          'severity': 'WARNING_HI',
          'format': 'Could not open file {}',
          'params': [{'kind': 'string', 'size': 40, 'name': 'fileName'}]},
  2312: { 'name': 'ServerDeployment.fileManager.CreateDirectorySucceeded',
          'severity': 'ACTIVITY_HI',
          'format': 'Created directory {} successfully',
          'params': [{'kind': 'string', 'size': 256, 'name': 'dirName'}]},
  16903: { 'name': 'ServerDeployment.fatalAdapter.AF_UNEXPECTED_ASSERT',
           'severity': 'FATAL',
           'format': 'Unexpected assert in file {}, line {}, args {}',
           'params': [ {'kind': 'string', 'size': 200, 'name': 'file'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'line'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'numArgs'}]},
  2053: { 'name': 'ServerDeployment.fileDownlink.DownlinkPartialWarning',
          'severity': 'WARNING_LO',
          'format': 'Offset {} plus length {} is greater than source size {} for partial downlink of file {} to file '
                    '{}. ',
          'params': [ {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'startOffset'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'length'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'filesize'},
                      {'kind': 'string', 'size': 100, 'name': 'sourceFileName'},
                      {'kind': 'string', 'size': 100, 'name': 'destFileName'}]},
  2317: { 'name': 'ServerDeployment.fileManager.ShellCommandStarted',
          'severity': 'ACTIVITY_HI',
          'format': 'Running shell command {}...',
          'params': [{'kind': 'string', 'size': 256, 'name': 'command'}]},
  2304: { 'name': 'ServerDeployment.fileManager.DirectoryCreateError',
          'severity': 'WARNING_HI',
          'format': 'Could not create directory {}, returned status {}',
          'params': [ {'kind': 'string', 'size': 256, 'name': 'dirName'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'status'}]},
  1539: { 'name': 'ServerDeployment.cmdSeq.CS_FileInvalid',
          'severity': 'WARNING_HI',
          'format': 'Sequence file {} invalid. Stage: {} Error: {}',
          'params': [ {'kind': 'string', 'size': 60, 'name': 'fileName'},
                      { 'kind': 'enum',
                        'representationType': {'name': 'I32', 'kind': 'integer', 'size': 32, 'signed': True},
                        'states': { 0: 'READ_HEADER',
                                    1: 'READ_HEADER_SIZE',
                                    2: 'DESER_SIZE',
                                    3: 'DESER_NUM_RECORDS',
                                    4: 'DESER_TIME_BASE',
                                    5: 'DESER_TIME_CONTEXT',
                                    6: 'READ_SEQ_CRC',
                                    7: 'READ_SEQ_DATA',
                                    8: 'READ_SEQ_DATA_SIZE'},
                        'name': 'stage'},
                      {'kind': 'integer', 'size': 32, 'signed': True, 'name': 'error'}]},
  1552: { 'name': 'ServerDeployment.cmdSeq.CS_UnexpectedCompletion',
          'severity': 'WARNING_HI',
          'format': 'Command complete status received while no sequences active. Opcode: {}',
          'params': [{'kind': 'integer', 'size': 32, 'signed': False, 'name': 'opcode'}]},
  2566: { 'name': 'ServerDeployment.fileUplink.PacketOutOfOrder',
          'severity': 'WARNING_HI',
          'format': 'Received packet {} after packet {}',
          'params': [ {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'packetIndex'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'lastPacketIndex'}]},
  2052: { 'name': 'ServerDeployment.fileDownlink.DownlinkTimeout',
          'severity': 'WARNING_HI',
          'format': 'Timeout occurred during downlink of file {} to file {}. Downlink has been canceled.',
          'params': [ {'kind': 'string', 'size': 100, 'name': 'sourceFileName'},
                      {'kind': 'string', 'size': 100, 'name': 'destFileName'}]},
  3333: { 'name': 'ServerDeployment.prmDb.PrmFileSaveComplete',
          'severity': 'ACTIVITY_HI',
          'format': 'Parameter file save completed. Wrote {} records.',
          'params': [{'kind': 'integer', 'size': 32, 'signed': False, 'name': 'records'}]},
  513: { 'name': 'ServerDeployment.rateGroup1.RateGroupCycleSlip',
         'severity': 'WARNING_HI',
         'format': 'Rate group cycle slipped on cycle {}',
         'params': [{'kind': 'integer', 'size': 32, 'signed': False, 'name': 'cycle'}]},
  8195: { 'name': 'ServerDeployment.health.HLTH_CHECK_ENABLE',
          'severity': 'ACTIVITY_HI',
          'format': 'Health checking set to {}',
          'params': [ { 'kind': 'enum',
                        'representationType': {'name': 'I32', 'kind': 'integer', 'size': 32, 'signed': True},
                        'states': {0: 'DISABLED', 1: 'ENABLED'},
                        'name': 'enabled'}]},
  1548: { 'name': 'ServerDeployment.cmdSeq.CS_RecordMismatch',
          'severity': 'WARNING_HI',
          'format': 'Sequence file {} header records mismatch: {} in header, found {} extra bytes.',
          'params': [ {'kind': 'string', 'size': 60, 'name': 'fileName'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'header_records'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'extra_bytes'}]},
  2048: { 'name': 'ServerDeployment.fileDownlink.FileOpenError',
          'severity': 'WARNING_HI',
          'format': 'Could not open file {}',
          'params': [{'kind': 'string', 'size': 100, 'name': 'fileName'}]},
  2568: { 'name': 'ServerDeployment.fileUplink.UplinkCanceled',
          'severity': 'ACTIVITY_HI',
          'format': 'Received CANCEL packet',
          'params': []},
  2817: { 'name': 'ServerDeployment.eventLogger.ID_FILTER_ENABLED',
          'severity': 'ACTIVITY_HI',
          'format': 'ID {} is filtered.',
          'params': [{'kind': 'integer', 'size': 32, 'signed': False, 'name': 'ID'}]},
  2308: { 'name': 'ServerDeployment.fileManager.ShellCommandFailed',
          'severity': 'WARNING_HI',
          'format': 'Shell command {} failed with status {}',
          'params': [ {'kind': 'string', 'size': 256, 'name': 'command'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'status'}]},
  3330: { 'name': 'ServerDeployment.prmDb.PrmDbFull',
          'severity': 'FATAL',
          'format': 'Parameter DB full when adding ID 0x{:x} ',
          'params': [{'kind': 'integer', 'size': 32, 'signed': False, 'name': 'Id'}]},
  16896: { 'name': 'ServerDeployment.fatalAdapter.AF_ASSERT_0',
           'severity': 'FATAL',
           'format': 'Assert in file {}, line {}',
           'params': [ {'kind': 'string', 'size': 200, 'name': 'file'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'line'}]},
  2055: { 'name': 'ServerDeployment.fileDownlink.SendDataFail',
          'severity': 'WARNING_HI',
          'format': 'Failed to send data packet from file {} at byte offset {}.',
          'params': [ {'kind': 'string', 'size': 100, 'name': 'sourceFileName'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'byteOffset'}]},
  2319: { 'name': 'ServerDeployment.fileManager.RemoveDirectoryStarted',
          'severity': 'ACTIVITY_HI',
          'format': 'Removing directory {}...',
          'params': [{'kind': 'string', 'size': 256, 'name': 'dirName'}]},
  16900: { 'name': 'ServerDeployment.fatalAdapter.AF_ASSERT_4',
           'severity': 'FATAL',
           'format': 'Assert in file {}, line {}: {} {} {} {}',
           'params': [ {'kind': 'string', 'size': 200, 'name': 'file'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'line'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'arg1'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'arg2'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'arg3'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'arg4'}]},
  2311: { 'name': 'ServerDeployment.fileManager.ShellCommandSucceeded',
          'severity': 'ACTIVITY_HI',
          'format': 'Shell command {} succeeded',
          'params': [{'kind': 'string', 'size': 256, 'name': 'command'}]},
  1282: { 'name': 'ServerDeployment.cmdDisp.OpCodeCompleted',
          'severity': 'COMMAND',
          'format': 'Opcode 0x{:x} completed',
          'params': [{'kind': 'integer', 'size': 32, 'signed': False, 'name': 'Opcode'}]},
  1542: { 'name': 'ServerDeployment.cmdSeq.CS_FileNotFound',
          'severity': 'WARNING_HI',
          'format': 'Sequence file {} not found.',
          'params': [{'kind': 'string', 'size': 60, 'name': 'fileName'}]},
  8192: { 'name': 'ServerDeployment.health.HLTH_PING_WARN',
          'severity': 'WARNING_HI',
          'format': 'Ping entry {} late warning',
          'params': [{'kind': 'string', 'size': 40, 'name': 'entry'}]},
  1557: { 'name': 'ServerDeployment.cmdSeq.CS_CmdStepped',
          'severity': 'ACTIVITY_HI',
          'format': 'Sequence {} command {} stepped',
          'params': [ {'kind': 'string', 'size': 60, 'name': 'filename'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'command'}]},
  2314: { 'name': 'ServerDeployment.fileManager.MoveFileSucceeded',
          'severity': 'ACTIVITY_HI',
          'format': 'Moved file {} to file {} successfully',
          'params': [ {'kind': 'string', 'size': 256, 'name': 'sourceFileName'},
                      {'kind': 'string', 'size': 256, 'name': 'destFileName'}]},
  8198: { 'name': 'ServerDeployment.health.HLTH_PING_UPDATED',
          'severity': 'ACTIVITY_HI',
          'format': 'Health ping for {} changed to WARN {} FATAL {}',
          'params': [ {'kind': 'string', 'size': 40, 'name': 'entry'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'warn'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'fatal'}]},
  1556: { 'name': 'ServerDeployment.cmdSeq.CS_SequenceTimeout',
          'severity': 'WARNING_HI',
          'format': 'Sequence {} timed out on command {}',
          'params': [ {'kind': 'string', 'size': 60, 'name': 'filename'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'command'}]},
  769: { 'name': 'ServerDeployment.rateGroup2.RateGroupCycleSlip',
         'severity': 'WARNING_HI',
         'format': 'Rate group cycle slipped on cycle {}',
         'params': [{'kind': 'integer', 'size': 32, 'signed': False, 'name': 'cycle'}]},
  768: { 'name': 'ServerDeployment.rateGroup2.RateGroupStarted',
         'severity': 'DIAGNOSTIC',
         'format': 'Rate group started.',
         'params': []},
  2051: { 'name': 'ServerDeployment.fileDownlink.DownlinkCanceled',
          'severity': 'ACTIVITY_HI',
          'format': 'Canceled downlink of file {} to file {}',
          'params': [ {'kind': 'string', 'size': 100, 'name': 'sourceFileName'},
                      {'kind': 'string', 'size': 100, 'name': 'destFileName'}]},
  2054: { 'name': 'ServerDeployment.fileDownlink.DownlinkPartialFail',
          'severity': 'WARNING_HI',
          'format': 'Error occurred during partial downlink of file {} to file {}. Offset {} greater than or equal to '
                    'source filesize {}.',
          'params': [ {'kind': 'string', 'size': 100, 'name': 'sourceFileName'},
                      {'kind': 'string', 'size': 100, 'name': 'destFileName'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'startOffset'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'filesize'}]},
  2816: { 'name': 'ServerDeployment.eventLogger.SEVERITY_FILTER_STATE',
          'severity': 'ACTIVITY_LO',
          'format': '{} filter state. {}',
          'params': [ { 'kind': 'enum',
                        'representationType': {'name': 'I32', 'kind': 'integer', 'size': 32, 'signed': True},
                        'states': { 0: 'WARNING_HI',
                                    1: 'WARNING_LO',
                                    2: 'COMMAND',
                                    3: 'ACTIVITY_HI',
                                    4: 'ACTIVITY_LO',
                                    5: 'DIAGNOSTIC'},
                        'name': 'severity'},
                      {'kind': 'bool', 'size': 8, 'name': 'enabled'}]},
  2318: { 'name': 'ServerDeployment.fileManager.CreateDirectoryStarted',
          'severity': 'ACTIVITY_HI',
          'format': 'Creating directory {}...',
          'params': [{'kind': 'string', 'size': 256, 'name': 'dirName'}]},
  2564: { 'name': 'ServerDeployment.fileUplink.InvalidReceiveMode',
          'severity': 'WARNING_HI',
          'format': 'Packet type {} received in mode {}',
          'params': [ {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'packetType'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'mode'}]},
  8194: { 'name': 'ServerDeployment.health.HLTH_PING_WRONG_KEY',
          'severity': 'FATAL',
          'format': 'Ping entry {} responded with wrong key 0x{:x}',
          'params': [ {'kind': 'string', 'size': 40, 'name': 'entry'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'badKey'}]},
  1551: { 'name': 'ServerDeployment.cmdSeq.CS_PortSequenceStarted',
          'severity': 'ACTIVITY_HI',
          'format': 'Local request for sequence {} started.',
          'params': [{'kind': 'string', 'size': 60, 'name': 'filename'}]},
  2567: { 'name': 'ServerDeployment.fileUplink.PacketDuplicate',
          'severity': 'WARNING_HI',
          'format': 'Received a duplicate of packet {}',
          'params': [{'kind': 'integer', 'size': 32, 'signed': False, 'name': 'packetIndex'}]},
  1547: { 'name': 'ServerDeployment.cmdSeq.CS_InvalidMode',
          'severity': 'WARNING_HI',
          'format': 'Invalid mode',
          'params': []},
  1025: { 'name': 'ServerDeployment.rateGroup3.RateGroupCycleSlip',
          'severity': 'WARNING_HI',
          'format': 'Rate group cycle slipped on cycle {}',
          'params': [{'kind': 'integer', 'size': 32, 'signed': False, 'name': 'cycle'}]},
  2569: { 'name': 'ServerDeployment.fileUplink.DecodeError',
          'severity': 'WARNING_HI',
          'format': 'Unable to decode file packet. Status: {}',
          'params': [{'kind': 'integer', 'size': 32, 'signed': True, 'name': 'status'}]},
  3334: { 'name': 'ServerDeployment.prmDb.PrmFileReadError',
          'severity': 'WARNING_HI',
          'format': 'Parameter file read failed in stage {} with record {} and error {}',
          'params': [ { 'kind': 'enum',
                        'representationType': {'name': 'I32', 'kind': 'integer', 'size': 32, 'signed': True},
                        'states': { 0: 'OPEN',
                                    1: 'DELIMITER',
                                    2: 'DELIMITER_SIZE',
                                    3: 'DELIMITER_VALUE',
                                    4: 'RECORD_SIZE',
                                    5: 'RECORD_SIZE_SIZE',
                                    6: 'RECORD_SIZE_VALUE',
                                    7: 'PARAMETER_ID',
                                    8: 'PARAMETER_ID_SIZE',
                                    9: 'PARAMETER_VALUE',
                                    10: 'PARAMETER_VALUE_SIZE'},
                        'name': 'stage'},
                      {'kind': 'integer', 'size': 32, 'signed': True, 'name': 'record'},
                      {'kind': 'integer', 'size': 32, 'signed': True, 'name': 'error'}]},
  2322: { 'name': 'ServerDeployment.fileManager.FileSizeSucceeded',
          'severity': 'ACTIVITY_HI',
          'format': 'The size of file {} is {} B',
          'params': [ {'kind': 'string', 'size': 256, 'name': 'fileName'},
                      {'kind': 'integer', 'size': 64, 'signed': False, 'name': 'size'}]},
  1538: { 'name': 'ServerDeployment.cmdSeq.CS_FileReadError',
          'severity': 'WARNING_HI',
          'format': 'Error reading sequence file {}',
          'params': [{'kind': 'string', 'size': 60, 'name': 'fileName'}]},
  3329: { 'name': 'ServerDeployment.prmDb.PrmIdUpdated',
          'severity': 'ACTIVITY_HI',
          'format': 'Parameter ID 0x{:x} updated',
          'params': [{'kind': 'integer', 'size': 32, 'signed': False, 'name': 'Id'}]},
  1285: { 'name': 'ServerDeployment.cmdDisp.InvalidCommand',
          'severity': 'WARNING_HI',
          'format': 'Invalid opcode 0x{:x} received',
          'params': [{'kind': 'integer', 'size': 32, 'signed': False, 'name': 'Opcode'}]},
  2056: { 'name': 'ServerDeployment.fileDownlink.SendStarted',
          'severity': 'ACTIVITY_HI',
          'format': 'Downlink of {} bytes started from {} to {}',
          'params': [ {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'fileSize'},
                      {'kind': 'string', 'size': 100, 'name': 'sourceFileName'},
                      {'kind': 'string', 'size': 100, 'name': 'destFileName'}]},
  1543: { 'name': 'ServerDeployment.cmdSeq.CS_FileCrcFailure',
          'severity': 'WARNING_HI',
          'format': 'Sequence file {} had invalid CRC. Stored 0x{:x}, Computed 0x{:x}.',
          'params': [ {'kind': 'string', 'size': 60, 'name': 'fileName'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'storedCRC'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'computedCRC'}]},
  1536: { 'name': 'ServerDeployment.cmdSeq.CS_SequenceLoaded',
          'severity': 'ACTIVITY_LO',
          'format': 'Loaded sequence {}',
          'params': [{'kind': 'string', 'size': 60, 'name': 'fileName'}]},
  1284: { 'name': 'ServerDeployment.cmdDisp.MalformedCommand',
          'severity': 'WARNING_HI',
          'format': 'Received malformed command packet. Status: {}',
          'params': [ { 'kind': 'enum',
                        'representationType': {'name': 'I32', 'kind': 'integer', 'size': 32, 'signed': True},
                        'states': { 0: 'OK',
                                    3: 'BUFFER_EMPTY',
                                    4: 'FORMAT_ERROR',
                                    5: 'SIZE_MISMATCH',
                                    6: 'TYPE_MISMATCH'},
                        'name': 'Status'}]},
  2320: { 'name': 'ServerDeployment.fileManager.MoveFileStarted',
          'severity': 'ACTIVITY_HI',
          'format': 'Moving file {} to file {}...',
          'params': [ {'kind': 'string', 'size': 256, 'name': 'sourceFileName'},
                      {'kind': 'string', 'size': 256, 'name': 'destFileName'}]},
  2818: { 'name': 'ServerDeployment.eventLogger.ID_FILTER_LIST_FULL',
          'severity': 'WARNING_LO',
          'format': 'ID filter list is full. Cannot filter {} .',
          'params': [{'kind': 'integer', 'size': 32, 'signed': False, 'name': 'ID'}]},
  1553: { 'name': 'ServerDeployment.cmdSeq.CS_ModeSwitched',
          'severity': 'ACTIVITY_HI',
          'format': 'Sequencer switched to {} step mode',
          'params': [ { 'kind': 'enum',
                        'representationType': {'name': 'I32', 'kind': 'integer', 'size': 32, 'signed': True},
                        'states': {0: 'STEP', 1: 'AUTO'},
                        'name': 'mode'}]},
  17408: { 'name': 'ServerDeployment.bufferManager.NoBuffsAvailable',
           'severity': 'WARNING_HI',
           'format': 'No available buffers of size {}',
           'params': [{'kind': 'integer', 'size': 32, 'signed': False, 'name': 'size'}]},
  2310: { 'name': 'ServerDeployment.fileManager.AppendFileSucceeded',
          'severity': 'ACTIVITY_HI',
          'format': 'Appended {} to the end of {}',
          'params': [ {'kind': 'string', 'size': 256, 'name': 'source'},
                      {'kind': 'string', 'size': 256, 'name': 'target'}]},
  2305: { 'name': 'ServerDeployment.fileManager.DirectoryRemoveError',
          'severity': 'WARNING_HI',
          'format': 'Could not remove directory {}, returned status {}',
          'params': [ {'kind': 'string', 'size': 256, 'name': 'dirName'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'status'}]},
  1289: { 'name': 'ServerDeployment.cmdDisp.TestCmd1Args',
          'severity': 'ACTIVITY_HI',
          'format': 'TEST_CMD_1 args: I32: {}, F32: {:f}, U8: {}',
          'params': [ {'kind': 'integer', 'size': 32, 'signed': True, 'name': 'arg1'},
                      {'kind': 'float', 'size': 32, 'name': 'arg2'},
                      {'kind': 'integer', 'size': 8, 'signed': False, 'name': 'arg3'}]},
  8197: { 'name': 'ServerDeployment.health.HLTH_CHECK_LOOKUP_ERROR',
          'severity': 'WARNING_LO',
          'format': "Couldn't find entry {}",
          'params': [{'kind': 'string', 'size': 40, 'name': 'entry'}]},
  3331: { 'name': 'ServerDeployment.prmDb.PrmIdAdded',
          'severity': 'ACTIVITY_HI',
          'format': 'Parameter ID 0x{:x} added',
          'params': [{'kind': 'integer', 'size': 32, 'signed': False, 'name': 'Id'}]},
  1558: { 'name': 'ServerDeployment.cmdSeq.CS_CmdStarted',
          'severity': 'ACTIVITY_HI',
          'format': 'Sequence {} started',
          'params': [{'kind': 'string', 'size': 60, 'name': 'filename'}]},
  1280: { 'name': 'ServerDeployment.cmdDisp.OpCodeRegistered',
          'severity': 'DIAGNOSTIC',
          'format': 'Opcode 0x{:x} registered to port {} slot {}',
          'params': [ {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'Opcode'},
                      {'kind': 'integer', 'size': 32, 'signed': True, 'name': 'port'},
                      {'kind': 'integer', 'size': 32, 'signed': True, 'name': 'slot'}]},
  8193: { 'name': 'ServerDeployment.health.HLTH_PING_LATE',
          'severity': 'FATAL',
          'format': 'Ping entry {} did not respond',
          'params': [{'kind': 'string', 'size': 40, 'name': 'entry'}]},
  1546: { 'name': 'ServerDeployment.cmdSeq.CS_CommandError',
          'severity': 'WARNING_HI',
          'format': 'Sequence file {}: Command {} (opcode {}) completed with error {}',
          'params': [ {'kind': 'string', 'size': 60, 'name': 'fileName'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'recordNumber'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'opCode'},
                      {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'errorStatus'}]},
  2050: { 'name': 'ServerDeployment.fileDownlink.FileSent',
          'severity': 'ACTIVITY_HI',
          'format': 'Sent file {} to file {}',
          'params': [ {'kind': 'string', 'size': 100, 'name': 'sourceFileName'},
                      {'kind': 'string', 'size': 100, 'name': 'destFileName'}]},
  3328: { 'name': 'ServerDeployment.prmDb.PrmIdNotFound',
          'severity': 'WARNING_LO',
          'format': 'Parameter ID 0x{:x} not found',
          'params': [{'kind': 'integer', 'size': 32, 'signed': False, 'name': 'Id'}]},
  1561: { 'name': 'ServerDeployment.cmdSeq.CS_NoRecords',
          'severity': 'WARNING_LO',
          'format': 'Sequence file {} has no records. Ignoring.',
          'params': [{'kind': 'string', 'size': 60, 'name': 'fileName'}]},
  16901: { 'name': 'ServerDeployment.fatalAdapter.AF_ASSERT_5',
           'severity': 'FATAL',
           'format': 'Assert in file {}, line {}: {} {} {} {} {}',
           'params': [ {'kind': 'string', 'size': 200, 'name': 'file'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'line'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'arg1'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'arg2'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'arg3'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'arg4'},
                       {'kind': 'integer', 'size': 32, 'signed': False, 'name': 'arg5'}]},
  1288: { 'name': 'ServerDeployment.cmdDisp.NoOpStringReceived',
          'severity': 'ACTIVITY_HI',
          'format': 'Received a NO-OP string={}',
          'params': [{'kind': 'string', 'size': 40, 'name': 'message'}]},
  17409: { 'name': 'ServerDeployment.bufferManager.NullEmptyBuffer',
           'severity': 'WARNING_HI',
           'format': 'Received null pointer and zero size buffer',
           'params': []},
  1537: { 'name': 'ServerDeployment.cmdSeq.CS_SequenceCanceled',
          'severity': 'ACTIVITY_HI',
          'format': 'Sequence file {} canceled',
          'params': [{'kind': 'string', 'size': 60, 'name': 'fileName'}]},
  1550: { 'name': 'ServerDeployment.cmdSeq.CS_TimeContextMismatch',
          'severity': 'WARNING_HI',
          'format': "Sequence file {}: Current time context doesn't match sequence context: base: {} seq: {}",
          'params': [ {'kind': 'string', 'size': 60, 'name': 'fileName'},
                      {'kind': 'integer', 'size': 8, 'signed': False, 'name': 'currTimeBase'},
                      {'kind': 'integer', 'size': 8, 'signed': False, 'name': 'seqTimeBase'}]},
  2321: { 'name': 'ServerDeployment.fileManager.RemoveFileStarted',
          'severity': 'ACTIVITY_HI',
          'format': 'Removing file {}...',
          'params': [{'kind': 'string', 'size': 256, 'name': 'fileName'}]},
  2563: { 'name': 'ServerDeployment.fileUplink.FileWriteError',
          'severity': 'WARNING_HI',
          'format': 'Could not write to file {}',
          'params': [{'kind': 'string', 'size': 40, 'name': 'fileName'}]}}


class FprimeEventConversion(Conversion):
    def __init__(self):
        super().__init__()
        self.converted_type = "STRING"
        self.converted_bit_size = 0

    def call(self, value, packet, buffer):
        event_id = packet.read("FPRIME_EVENT_ID", "RAW", buffer)
        event = EVENTS.get(event_id)
        if event is None:
            return f"Unknown event id {event_id}"
        try:
            data = packet.read("FPRIME_EVENT_DATA", "RAW", buffer) or b""
            args = []
            offset = 0
            for p in event["params"]:
                v, offset = _parse_param(data, offset, p)
                args.append(v)
            return event["format"].format(*args)
        except Exception as exc:
            return f"Error formatting event {event['name']} (id={event_id}): {exc}"
